project_id = "boipukusgnipdxwmlbeb"

[auth.email]
otp_length = 6
otp_expiry = 600

[auth.email.template.confirmation]
subject = "Votre code de vérification Pr@mpt"
content_path = "./supabase/templates/confirmation.html"

[functions.process-email-queue]
verify_jwt = true