project_id = "boipukusgnipdxwmlbeb"

[auth]
  [auth.email]
    otp_expiry = 600
    otp_length = 6
    [auth.email.template]
      [auth.email.template.confirmation]
        content_path = "./supabase/templates/confirmation.html"
        subject = "Votre code de vérification Tornado"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
